#!/bin/sh
TMPFILE1=$(mktemp im1.XXXXXX)
TMPFILE2=$(mktemp im2.XXXXXX)

trap "rm -f $TMPFILE1 $TMPFILE2; exit 1" INT

cat /proc/interrupts > $TMPFILE1
sleep 2
cat /proc/interrupts > $TMPFILE2

diff $TMPFILE1 $TMPFILE2
rm -f $TMPFILE1 $TMPFILE2
